### ISSUE TITLE
Heap out of memory when using Grafana's live mode

### ISSUE THREAD

**Issue by Bingmang** [metrico/qryn#171]
Hi, first of all, this is a great project, I would love to use this project in production, but there is a OOM case when I use it.

When I using "Live mode" on Grafana Loki Explore, the qryn container's memory will keep increasing, and when I stop the live mode, the memory will be free after about 2 minutes.

Not in live mode:
```
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
fd365e6ae9c9   vector         3.92%     39.39MiB / 7.603GiB   0.51%     301MB / 294MB     37.8MB / 0B       10
bcaf3bb151f0   loki-adapter   4.01%     97.18MiB / 7.603GiB   1.25%     1.24GB / 608MB    7MB / 123kB       24
```

In live mode about 5 minutes:
```
CONTAINER ID   NAME           CPU %     MEM USAGE / LIMIT     MEM %     NET I/O           BLOCK I/O         PIDS
fd365e6ae9c9   vector         1.94%     41.48MiB / 7.603GiB   0.53%     315MB / 308MB     37.8MB / 0B       10
bcaf3bb151f0   loki-adapter   43.30%    1.145GiB / 7.603GiB   15.07%    1.81GB / 630MB    7MB / 123kB       24
```

qryn's log when OOM:

```
<--- Last few GCs --->

[26:0x608cd40]  8788818 ms: Scavenge (reduce) 2039.2 (2048.0) -> 2038.4 (2048.0) MB, 10.4 / 0.0 ms  (average mu = 0.378, current mu = 0.406) allocation failure 
[26:0x608cd40]  8788883 ms: Scavenge (reduce) 2039.3 (2045.0) -> 2038.5 (2046.0) MB, 14.2 / 0.0 ms  (average mu = 0.378, current mu = 0.406) allocation failure 
[26:0x608cd40]  8788900 ms: Scavenge (reduce) 2039.3 (2045.0) -> 2038.5 (2046.2) MB, 8.5 / 0.0 ms  (average mu = 0.378, current mu = 0.406) task 


<--- JS stacktrace --->

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 0xa3aaf0 node::Abort() [node]
 2: 0x970199 node::FatalError(char const*, char const*) [node]
 3: 0xbba42e v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, bool) [node]
 4: 0xbba7a7 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, bool) [node]
 5: 0xd769c5  [node]
 6: 0xd7754f  [node]
 7: 0xd8538b v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 8: 0xd868d7 v8::internal::Heap::FinalizeIncrementalMarkingIfComplete(v8::internal::GarbageCollectionReason) [node]
 9: 0xd8acd2 v8::internal::IncrementalMarkingJob::Task::RunInternal() [node]
10: 0xcae38b non-virtual thunk to v8::internal::CancelableTask::Run() [node]
11: 0xaa98b4 node::PerIsolatePlatformData::RunForegroundTask(std::unique_ptr<v8::Task, std::default_delete<v8::Task> >) [node]
12: 0xaab719 node::PerIsolatePlatformData::FlushForegroundTasksInternal() [node]
13: 0x13c0a86  [node]
14: 0x13d2ff4  [node]
15: 0x13c13d8 uv_run [node]
16: 0xa7b642 node::NodeMainInstance::Run() [node]
17: 0xa03805 node::Start(int, char**) [node]
18: 0x7fd1f56e42e1 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
19: 0x98c58c  [node]
Aborted (core dumped)
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! qryn@2.1.2 start: `node qryn.js`
npm ERR! Exit status 134
npm ERR! 
npm ERR! Failed at the qryn@2.1.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-24T11_06_29_741Z-debug.log
```

```
root@e68633271aff:/app# cat /root/.npm/_logs/2022-06-24T11_06_29_741Z-debug.log
```

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'start' ]
2 info using npm@6.14.17
3 info using node@v14.19.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle qryn@2.1.2~prestart: qryn@2.1.2
6 info lifecycle qryn@2.1.2~start: qryn@2.1.2
7 verbose lifecycle qryn@2.1.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle qryn@2.1.2~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
9 verbose lifecycle qryn@2.1.2~start: CWD: /app
10 silly lifecycle qryn@2.1.2~start: Args: [ '-c', 'node qryn.js' ]
11 silly lifecycle qryn@2.1.2~start: Returned: code: 134  signal: null
12 info lifecycle qryn@2.1.2~start: Failed to exec start script
13 verbose stack Error: qryn@2.1.2 start: `node qryn.js`
13 verbose stack Exit status 134
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:400:28)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:400:28)
13 verbose stack     at maybeClose (internal/child_process.js:1088:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:296:5)
14 verbose pkgid qryn@2.1.2
15 verbose cwd /app
16 verbose Linux 3.10.0-1160.el7.x86_64
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
18 verbose node v14.19.3
19 verbose npm  v6.14.17
20 error code ELIFECYCLE
21 error errno 134
22 error qryn@2.1.2 start: `node qryn.js`
22 error Exit status 134
23 error Failed at the qryn@2.1.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 134, true ]
```

**Comment by lmangani** [comment]
@Bingmang did you [allocate more memory](https://medium.com/weekly-webtips/increase-node-js-memory-limit-bonus-pm2-62cda081ce2a) to the process to cope with the load? Ie;

```
pm2 start qryn.js --node-args="--max-old-space-size=2048" # increase to 2gb
```

**Comment by lmangani** [comment]
@Bingmang this this help?

**Comment by Bingmang** [comment]
Hi @lmangani, thank you but the problem still exists. 

The question is that the memory keeps increasing in live mode, no matter how large the heap size is. 

I guess the reason may be that the previous query results is stored in memory in live mode and not freed, so the memory keeps increasing?

It is easy to reproduce, you can open several tabs at the same time, all open live mode, and then you can see that the qryn's memory is keep increasing. (one tab will also, but slower).

**Comment by Bingmang** [comment]
@akvlad Great! It worked. I would like to suggest setting the flushTimer's interval to 1000ms or 500ms, otherwise the CPU usage will be a bit high, the impact on live mode experience is almost negligible. Or you can set it as a configurable parameter.

Thanks for your quick support!

**Comment by akvlad** [comment]
fixed in https://github.com/metrico/qryn/pull/177
