### ISSUE TITLE
TLS/SSL error "unable to verify first certificate"

### ISSUE THREAD

**Issue by smmstf** [metrico/qryn#179]
Hello, i have this error when i try to set TLS between clickhouse and cloki. 
Before setting tls everything worked well.
Any idea please ?

`loki                   | > qryn@2.1.2 start /app
loki                   | > node qryn.js
loki                   | 
loki                   | {"level":30,"time":1657014852345,"pid":19,"hostname":"ringover","name":"qryn","msg":"Initializing DB... test"}
loki                   | {"level":30,"time":1657014852576,"pid":19,"hostname":"ringover","name":"qryn","msg":"Server listening at http://172.30.102.243:3100"}
loki                   | {"level":30,"time":1657014852576,"pid":19,"hostname":"ringover","name":"qryn","msg":"Qryn API up"}
loki                   | {"level":30,"time":1657014852576,"pid":19,"hostname":"ringover","name":"qryn","msg":"Qryn API listening on http://172.30.102.243:3100"}
loki                   | {"level":30,"time":1657014852579,"pid":19,"hostname":"ringover","name":"qryn","msg":"xxh ready"}
loki                   | {"level":50,"time":1657014852582,"pid":19,"hostname":"ringover","name":"qryn","err":"unable to verify the first certificate\nError: unable to verify the first certificate\n    at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)\n    at TLSSocket.emit (events.js:400:28)\n    at TLSSocket._finishInit (_tls_wrap.js:937:8)\n    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)","msg":"Error starting qryn"}
loki                   | npm ERR! code ELIFECYCLE
loki                   | npm ERR! errno 1
loki                   | npm ERR! qryn@2.1.2 start: `node qryn.js`
loki                   | npm ERR! Exit status 1
loki                   | npm ERR! 
loki                   | npm ERR! Failed at the qryn@2.1.2 start script.
loki                   | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
loki                   | 
loki                   | npm ERR! A complete log of this run can be found in:
loki                   | npm ERR!     /root/.npm/_logs/2022-07-05T09_54_12_606Z-debug.log
`

**Comment by lmangani** [comment]
Hello @smmstf 
Could you share more details - is the cert self-signed? is it a valid certificate?

`NODE_TLS_REJECT_UNAUTHORIZED=0 ` should make this pass insecurely but it should be be ignored as apparently your system thinks the remote chain is missing the intermediate certificate

**Comment by smmstf** [comment]
No it's not self-signed certificate, i generated my own ca.
Here are my env variables, is something missing ?

`      - HOST=172.30.102.243
      - CLICKHOUSE_SERVER=172.30.102.243
      - CLICKHOUSE_PORT=8443
      - CLICKHOUSE_PROTO= https
      - CLICKHOUSE_DB=test
      - CLICKHOUSE_AUTH=admin:admin
      - DEBUG=true
      - NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by lmangani** [comment]
You're most welcome!
