### ISSUE TITLE
Unexpected request content-type

### ISSUE THREAD

**Issue by lyl2008dsg** [metrico/qryn#218]
### when use Clickhouse MV, qryn will report this `Unexpected request content-type`

* CREATE MATERIALIZED
```sql
CREATE MATERIALIZED VIEW default.influx_log_send
ENGINE = URL('http://qryn:3100/influx/api/v2/write', 'LineAsString')
AS SELECT format('syslog,level={0},logger_name={1} message="{2}" {3}', 
  toString(level), 
  replaceRegexpAll(toString(logger_name), '[^a-zA-Z0-9_]', '_'), 
  replaceAll(replaceRegexpAll(message, '["\\\\]', '\x00\\0'), '\x00', '\\'), 
  toString(toUnixTimestamp64Nano(event_time_microseconds))) FROM system.text_log;

```

* system.text_log
```
"syslog,level=Information,logger_name=DNSCacheUpdater message=""Update period 15 seconds"" 1664249024429043000"
"syslog,level=Information,logger_name=Application message=""Available RAM: 27.34 GiB; physical cores: 1; logical cores: 48."" 1664249024429148000"
"syslog,level=Debug,logger_name=DNSResolver message=""Updating DNS cache"" 1664249024429179000"
"syslog,level=Debug,logger_name=DNSResolver message=""Updated DNS cache"" 1664249024429497000"

```

* qryn error log `Unexpected request content-type`
```log
qryn_1  | {"level":30,"time":1664335138357,"pid":19,"hostname":"0d02db9b0633","name":"qryn","reqId":"req-1rr","req":{"method":"POST","url":"/influx/api/v2/write","hostname":"172.24.177.11","remoteAddress":"172.17.0.1","remotePort":62050},"msg":"incoming request"}
qryn_1  | {"level":50,"time":1664335138589,"pid":19,"hostname":"0d02db9b0633","name":"qryn","reqId":"req-1rr","err":"Unexpected request content-type\nError: Unexpected request content-type\n    at genericJSONOrYAMLParser (/app/qryn.js:207:11)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async Parser.fn (/app/qryn.js:370:12)","msg":"Unexpected request content-type"}
qryn_1  | {"level":30,"time":1664335138590,"pid":19,"hostname":"0d02db9b0633","name":"qryn","reqId":"req-1rr","res":{"statusCode":200},"responseTime":233.03822302818298,"msg":"request completed"}
```

###  tried to use curl , it worked

* push curl
```
curl -i -XPOST 'http://127.0.0.1:3100/influx/api/v2/write' \
  --data-raw 'syslog,appname=myapp123,facility=console,host=myhost,hostname=myhost,severity=warning facility_code=14i,message="warning message here",severity_code=4i,procid="12345",timestamp=1434055562000000000,version=1'
``` 

* qryn success log
```
qryn_1  | {"level":30,"time":1664335853616,"pid":19,"hostname":"0d02db9b0633","name":"qryn","reqId":"req-1ue","req":{"method":"POST","url":"/influx/api/v2/write","hostname":"127.0.0.1:3100","remoteAddress":"172.17.0.1","remotePort":62404},"msg":"incoming request"}
qryn_1  | {"level":50,"time":1664335853617,"pid":19,"hostname":"0d02db9b0633","name":"qryn","reqId":"req-1ue","msg":"POST INFLUX /write"}
qryn_1  | [
qryn_1  |   { facility_code: 14 },
qryn_1  |   { message: 'warning message here' },
qryn_1  |   { severity_code: 4 },
qryn_1  |   { procid: '12345' },
qryn_1  |   { timestamp: 1434055562000000000 },
qryn_1  |   { version: 1 }
qryn_1  | ]
qryn_1  | {"level":30,"time":1664335853619,"pid":19,"hostname":"0d02db9b0633","name":"qryn","reqId":"req-1ue","res":{"statusCode":200},"responseTime":2.5179669857025146,"msg":"request completed"}

```

### try to look at the source code, I feel that there is no parsing of `lineAsString` format here?

* JSON.parse(body) 
* yaml.parse(body)
* parse lineAsString ?
```javascript

async function genericJSONOrYAMLParser (req) {
  try {
    const tempoPush = await parseTempoPush(req)
    if (tempoPush) {
      return tempoPush
    }
    const length = getContentLength(req, 1e9)
    if (req.routerPath === '/loki/api/v1/push' && length > 5e6) {
      return
    }
    await shaper.register(length)
    const body = await getContentBody(req)
    try { return JSON.parse(body) } catch (e) {}
    try { return yaml.parse(body) } catch (e) {}
    throw new Error('Unexpected request content-type')
  } catch (err) {
    err.statusCode = 400
    throw err
  }
}

```

### version info

node v14.20.1
npm  6.14.17
ClickHouse server version 22.2.2.1.
qryn 2.1.29

**Comment by akvlad** [comment]
@lyl2008dsg please check the https://github.com/metrico/qryn/pull/219 PR if possible.
Please check if your setup works with this fix.

**Comment by lyl2008dsg** [comment]
Thanks a lot, qryn is working, I'll follow on it's release.

**Comment by lmangani** [comment]
Merged and released! Thanks @lyl2008dsg for your report and the assistance validating the patch!
