### ISSUE TITLE
span.attributes is not iterable

### ISSUE THREAD

**Issue by Cluas** [metrico/qryn#259]
```bash
{"level":50,"time":1669098698722,"pid":19,"hostname":"qryn-6cb5c598d9-wdcxj","name":"qryn","reqId":"req-4ibz","err":"span.attributes is not iterable\nTypeError: span.attributes is not iterable\n    at /app/lib/handlers/otlp_push.js:51:19\n    at Array.map (<anonymous>)\n    at Object.handler (/app/lib/handlers/otlp_push.js:48:33)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:110:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:74:7)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:177:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at done (/app/node_modules/fastify/lib/contentTypeParser.js:171:14)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:165:27","msg":"span.attributes is not iterable"}
{"level":50,"time":1669098713601,"pid":19,"hostname":"qryn-6cb5c598d9-wdcxj","name":"qryn","reqId":"req-4ic8","err":"span.attributes is not iterable\nTypeError: span.attributes is not iterable\n    at /app/lib/handlers/otlp_push.js:51:19\n    at Array.map (<anonymous>)\n    at Object.handler (/app/lib/handlers/otlp_push.js:48:33)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:110:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:74:7)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:177:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at done (/app/node_modules/fastify/lib/contentTypeParser.js:171:14)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:165:27","msg":"span.attributes is not iterable"}
{"level":50,"time":1669098719089,"pid":19,"hostname":"qryn-6cb5c598d9-wdcxj","name":"qryn","reqId":"req-4icb","err":"span.attributes is not iterable\nTypeError: span.attributes is not iterable\n    at /app/lib/handlers/otlp_push.js:51:19\n    at Array.map (<anonymous>)\n    at Object.handler (/app/lib/handlers/otlp_push.js:48:33)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:110:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:74:7)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:177:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at done (/app/node_modules/fastify/lib/contentTypeParser.js:171:14)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:165:27","msg":"span.attributes is not iterable"}
{"level":50,"time":1669098743383,"pid":19,"hostname":"qryn-6cb5c598d9-wdcxj","name":"qryn","reqId":"req-4icu","err":"span.attributes is not iterable\nTypeError: span.attributes is not iterable\n    at /app/lib/handlers/otlp_push.js:51:19\n    at Array.map (<anonymous>)\n    at Object.handler (/app/lib/handlers/otlp_push.js:48:33)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:110:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:74:7)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:177:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at done (/app/node_modules/fastify/lib/contentTypeParser.js:171:14)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:165:27","msg":"span.attributes is not iterable"}
{"level":50,"time":1669098749278,"pid":19,"hostname":"qryn-6cb5c598d9-wdcxj","name":"qryn","reqId":"req-4id9","err":"span.attributes is not iterable\nTypeError: span.attributes is not iterable\n    at /app/lib/handlers/otlp_push.js:51:19\n    at Array.map (<anonymous>)\n    at Object.handler (/app/lib/handlers/otlp_push.js:48:33)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:110:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:74:7)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:177:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at done (/app/node_modules/fastify/lib/contentTypeParser.js:171:14)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:165:27","msg":"span.attributes is not iterable"}
{"level":50,"time":1669098774017,"pid":19,"hostname":"qryn-6cb5c598d9-wdcxj","name":"qryn","reqId":"req-4idw","err":"span.attributes is not iterable\nTypeError: span.attributes is not iterable\n    at /app/lib/handlers/otlp_push.js:51:19\n    at Array.map (<anonymous>)\n    at Object.handler (/app/lib/handlers/otlp_push.js:48:33)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:110:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:74:7)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:177:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at done (/app/node_modules/fastify/lib/contentTypeParser.js:171:14)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:165:27","msg":"span.attributes is not iterable"}
{"level":50,"time":1669098793685,"pid":19,"hostname":"qryn-6cb5c598d9-wdcxj","name":"qryn","reqId":"req-4iei","err":"span.attributes is not iterable\nTypeError: span.attributes is not iterable\n    at /app/lib/handlers/otlp_push.js:51:19\n    at Array.map (<anonymous>)\n    at Object.handler (/app/lib/handlers/otlp_push.js:48:33)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:126:28)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:110:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:74:7)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:177:9\n    at AsyncResource.runInAsyncScope (node:async_hooks:203:9)\n    at done (/app/node_modules/fastify/lib/contentTypeParser.js:171:14)\n    at /app/node_modules/fastify/lib/contentTypeParser.js:165:27","msg":"span.attributes is not iterable"}
```

**Comment by lmangani** [comment]
Could you provide an example insert?

**Comment by Cluas** [comment]
> Could you provide an example insert?

https://github.com/parca-dev/parca/blob/main/scripts/local-tracing/README.md

Only this sevice can't not export tracing data.

**Comment by Cluas** [comment]
I'm new to node js, but with my intuition and the results I've tested, I think it's because there's no null determination here, and some services do have spans that don't carry any attributes. like parca.
