### ISSUE TITLE
Unability to use days and weeks as interval

### ISSUE THREAD

**Issue by MalKeshar** [metrico/qryn#261]
1. Using h(hours) or d(days) as interval leads to error "Expected [ 'ns', 'us', or 'ms' ] ". At the same time it works in the original loki.
query:
```
count(count_over_time({log_name="web",log_level="ERROR"}[1h])) by(host)
```
err:
```
Couldn't execute script:
Expected [ 'ns', 'us', or 'ms' ] @1:81 encountered '])'.
```

2. As interval I can use duration: s,m,h even error in the log mention only ns,us,ms.

query_range: 90d, so query_range>interval
qryn version: v2.1.47

Full error
```
{"level":30,"time":1669214029326,"pid":19,"hostname":"dd1b6b30bf34","name":"qryn","reqId":"req-i","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1669214029065000000&limit=10&query=count%28count_over_time%28%7Blog_name%3D%22web%22%2Clog_level%3D%22ERROR%22%7D%5B1w%5D%29%29+by%28host%29&start=1661438029065000000&step=3600000ms","hostname":"[cloki1.xxx.xxx](http://cloki1.xxx.xxx/):3100","remoteAddress":"172.25.51.11","remotePort":53590},"msg":"incoming request"}
Couldn't execute script:
Expected [ 'ns', 'us', or 'ms' ] @1:81 encountered '])'.
count(count_over_time({log_name="web",log_level="ERROR"}[1w])) by(host)
{"level":50,"time":1669214030972,"pid":19,"hostname":"dd1b6b30bf34","name":"qryn","reqId":"req-i","err":"Cannot read properties of null (reading 'rootToken')\nTypeError: Cannot read properties of null (reading 'rootToken')\n    at Object.module.exports.transpile (/app/parser/transpiler.js:90:28)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:219:29)\n    at Object.handler (/app/lib/handlers/query_range.js:40:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","msg":"Cannot read properties of null (reading 'rootToken')"}
{"level":30,"time":1669214030972,"pid":19,"hostname":"dd1b6b30bf34","name":"qryn","reqId":"req-i","res":{"statusCode":200},"responseTime":1645.6601734161377,"msg":"request completed"}
{"level":30,"time":1669214037897,"pid":19,"hostname":"dd1b6b30bf34","name":"qryn","reqId":"req-j","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1669214037645000000&limit=10&query=count%28count_over_time%28%7Blog_name%3D%22web%22%2Clog_level%3D%22ERROR%22%7D%5B1d%5D%29%29+by%28host%29&start=1661438037645000000&step=3600000ms","hostname":"[cloki1.xxx.xxx](http://cloki1.xxx.xxx/):3100","remoteAddress":"172.25.51.11","remotePort":53590},"msg":"incoming request"}
Couldn't execute script:
Expected [ 'ns', 'us', or 'ms' ] @1:81 encountered '])'.
count(count_over_time({log_name="web",log_level="ERROR"}[1d])) by(host)
{"level":50,"time":1669214039430,"pid":19,"hostname":"dd1b6b30bf34","name":"qryn","reqId":"req-j","err":"Cannot read properties of null (reading 'rootToken')\nTypeError: Cannot read properties of null (reading 'rootToken')\n    at Object.module.exports.transpile (/app/parser/transpiler.js:90:28)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:219:29)\n    at Object.handler (/app/lib/handlers/query_range.js:40:16)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)","msg":"Cannot read properties of null (reading 'rootToken')"}
{"level":30,"time":1669214039431,"pid":19,"hostname":"dd1b6b30bf34","name":"qryn","reqId":"req-j","res":{"statusCode":200},"responseTime":1533.942099571228,"msg":"request completed"}
```

**Comment by lmangani** [comment]
I do not have a 90d test setup with with up to 7d I cannot replicate this issue. I've tried incrementally.

Count over time and grouping seem to work fine:
> count_over_time({forwarder="vector"} [$__interval]) by (type)

Count of Count over time and grouping also seems to work fine:
> count(count_over_time({forwarder="vector"} [$__interval])) by (type)

I've tried different range types and could not obtain the same error message with qryn `2.1.50`

Are you forming and running queries using Grafana? They appear to have human generated spacing.

**Comment by MalKeshar** [comment]
With dynamic $__interval all fine. I guess because it's always use minutes/seconds under the hood. 
Problem appears if you choose exact interval type, like [1h].

**Comment by akvlad** [comment]
@MalKeshar  The branch https://github.com/metrico/qryn/tree/issue_261_duration_support includes a solution for you. 
But the merge will happen after the holidays, I think.
Feel free to check.

**Comment by akvlad** [comment]
The branch was added to the beta release (2.1.58-beta)

**Comment by Dletta** [comment]
We have tested and merged. Days (d) and Weeks (w) are now accepted inside the query.
