### ISSUE TITLE
Max size of regex string for a label comparison

### ISSUE THREAD

**Issue by MalKeshar** [metrico/qryn#263]
Please point me, what is the max size for the regex pattern for the label comparison?
I have the query which fails with "RangeError: Maximum call stack size exceeded" on qryn. 
The same query works on original loki.
String became that big due to grafana variable substitution from the list of the possible label values. Probably bad idea.

```
{"level":30,"time":1669396029698,"pid":19,"hostname":"f218d152e3fb","name":"qryn","reqId":"req-3","req":{"method":"GET","url":"/loki/api/v1/query?direction=backward&limit=1000&query=sum+by%28tag_log_name%29%28count_over_time%28%7Btag_log_name%3D%22zabbix-web-error%22%2Ctag_log_level%3D~%22ERROR%22%2Ctag_host_dns%3D~%22%5E%28webslave%7Cweblu%7Cwebmaster%29.%2A%24%22%2Ctag_class%3D~%22_huge_string_1681_bytes_%22%7D+%5B172800s%5D%29%29+&time=1669396029602000000","hostname":"cloki1.mhd.local:3100","remoteAddress":"172.25.51.11","remotePort":34536},"msg":"incoming request"}
RangeError: Maximum call stack size exceeded
    at getOwnPropertyDescriptor (<anonymous>)
    at getConstructorName (node:internal/util/inspect:592:24)
    at formatRaw (node:internal/util/inspect:851:23)
    at formatValue (node:internal/util/inspect:841:10)
    at inspect (node:internal/util/inspect:365:10)
    at formatWithOptionsInternal (node:internal/util/inspect:2292:40)
    at formatWithOptions (node:internal/util/inspect:2154:10)
    at console.value (node:internal/console/constructor:339:14)
    at console.log (node:internal/console/constructor:376:61)
    at consoleCall (<anonymous>)
QLITERALCHARS Grammar not found
Couldn't execute script:
Expected [ or 'SYNTAX' ] @1:0 encountered 'sum b'.
sum by(tag_log_name)(count_over_time({tag_log_name="zabbix-web-error",tag_log_level=~"ERROR",tag_host_dns=~"^(webslave|weblu|webmaster).*$",tag_class=~"_huge_string_1681_bytes_"} [172800s]))

{"level":50,"time":1669396030083,"pid":19,"hostname":"f218d152e3fb","name":"qryn","reqId":"req-3","err":"invalid request\nBad Request: invalid request\n    at Object.module.exports.transpile (/app/parser/transpiler.js:92:11)\n    at Object.instantQueryScan (/app/lib/db/clickhouse.js:238:29)\n    at Object.handler (/app/lib/handlers/query.js:16:16)\n    at preHandlerCallback (/app/node_modules/fastify/lib/handleRequest.js:128:37)\n    at preValidationCallback (/app/node_modules/fastify/lib/handleRequest.js:112:5)\n    at handler (/app/node_modules/fastify/lib/handleRequest.js:76:7)\n    at handleRequest (/app/node_modules/fastify/lib/handleRequest.js:24:5)\n    at runPreParsing (/app/node_modules/fastify/lib/route.js:528:5)\n    at next (/app/node_modules/fastify/lib/hooks.js:168:7)\n    at /app/node_modules/@fastify/cors/index.js:130:12","msg":"invalid request"}
```

**Comment by akvlad** [comment]
We haven't tested the parser library against the maximum size of expression it can process.
But as far as it uses recursion to parse, I don't think it's possible to make the request too big.

**Comment by lmangani** [comment]
All you have to do is this: https://qryn.metrico.in/#/env?id=node-parameters
