### ISSUE TITLE
Missing columns: 'timestamp_ns'

### ISSUE THREAD

**Issue by StevenCyb** [metrico/qryn#310]
I deployed QRYN `qxip/qryn:v2.2.18` together with Clickhouse `docker.io/bitnami/clickhouse:23.2.4-debian-11-r0` on Kubernetes `v1.24.8`. After that I added QRYN as Tempo datasource in Grafana, which shows success. Then I wrote some dummy spans using opentelemetry and opentracing. I checked the logs, and everything was fine so I opened the explorer in Grafana where my service and span name was shown. But the query didn't return any results.
The only thing I found was this error log in the CRYN container:
```json
{
   "level":30,
   "time":1678903350478,
   "pid":18,
   "hostname":"...-shard0-0",
   "name":"qryn",
   "reqId":"req-9",
   "req":{
      "method":"GET",
      "url":"/api/search?tags=%20service.name%3D%22demo-service%22&limit=20&start=1678899750&end=1678903350",
      "hostname":"...",
      "remoteAddress":"10.10.1.124",
      "remotePort":47562
   },
   "msg":"incoming request"
}
{
   "level":50,
   "time":1678903350484,
   "pid":18,
   "hostname":"...-shard0-0",
   "name":"qryn",
   "reqId":"req-9",
   "err":"Error: Request failed with status code 404\nResponse: [404] Cod   > e: 47. DB::Exception: Missing columns: 'timestamp_ns' while processing query: 'SELECT trace_id, span_id FROM (SELECT trace_id, span_id FROM qryn.tempo_traces_attrs_gin WHERE (oid = // / '0') AND (date >= '2023-03-15') AND (date <= '2023-03-15') AND (key = 'service.name') AND (val = 'demo-service') AND (timestamp_ns >= 1678899750000000000) AND (timestamp_ns <= 167890     3350000000000)) AS rawsubsel ORDER BY timestamp_ns DESC LIMIT 20', required columns: 'trace_id' 'span_id' 'timestamp_ns' 'trace_id' 'span_id' 'timestamp_ns'. (UNKNOWN_IDENTIFIER) ( ────version 23.2.4.12 (official build))\n\nError: Request failed with status code 404\n    at createError (/app/node_modules/axios/lib/core/createError.js:16:15)\n    at settle (/app/node_modules/axios/lib/core/settle.js:17:12)\n    at IncomingMessage.handleStreamEnd (/app/node_modules/axios/lib/adapters/http.js:269:11)\n    at IncomingMessage.emit (node:events:│.i t525:35)\n    at endReadableNT (node:internal/streams/readable:1358:12)\n    at processTicksAndRejections (node:internal/process/task_queues:83:21)",
   "msg":"Request failed with status code 404"
}
```

As far as I understand `timestamp_ns` is something that should be defined by CRYN. Is this a bug or did I do something wrong?

**Comment by akvlad** [comment]
@StevenCyb sorry. Just merged this bugfix to the master.
Please recheck `v2.2.19`. Please tell us if the bug persists.

**Comment by StevenCyb** [comment]
Perfect! Yes `v2.2.19` resolved my problem.
