### ISSUE TITLE
Json parser didnt work 

### ISSUE THREAD

**Issue by xom4ek** [metrico/qryn#343]
After try usage this filter into grafana

<img width="1398" alt="image" src="https://github.com/metrico/qryn/assets/29627495/b824ab3d-2fa8-4a66-bf32-616de09d1284">

logQL `{cluster="helloworld"} | json | app_kubernetes_io_name = "hello-world"}`

`qryn` closed with fatal error
<details open>
  <summary>Crash logs</summary>
 
```logs
{"level":30,"time":1692622696873,"pid":20,"hostname":"qryn-7d9bb45b4b-q2p7v","name":"qryn","reqId":"req-i","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1692622696609000000&limit=1000&query=%7Bcluster%3D%22helloworld%22%7D+%7C+json+%7C+app_kubernetes_io_name+%3D+%60hello-world%60&start=1692622636609000000&step=50ms","hostname":"qryn.qryn.svc:3100","remoteAddress":"10.0.4.131","remotePort":59422},"msg":"incoming request"}
node:events:491
      throw er; // Unhandled 'error' event
      ^

<ref *1> StreamError: Cannot read properties of undefined (reading 'EOF')
    at /app/node_modules/scramjet-core/lib/util/mk-transform.js:59:44
  caused by:
    at module.exports.isEOF (/app/parser/registry/common.js:121:37)
    ... 2 lines matching cause stack trace ...
    at async Promise.all (index 0)
  --- raised in DataStream(20) constructed ---
    at new PromiseTransformStream (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:65:27)
    at new DataStream (/app/node_modules/scramjet-core/lib/data-stream.js:43:9)
    at StringStream.map (/app/node_modules/scramjet-core/lib/data-stream.js:197:26)
    at preprocessStream (/app/lib/db/clickhouse.js:816:6)
    at queryFingerprintsScan (/app/lib/db/clickhouse.js:369:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler (/app/lib/handlers/query_range.js:40:22) {
  chunk: '{"string":"  warnings.warn(","fingerprint":"2268018183592429208","timestamp_ns":"1692622650649535910","labels":[["app_kubernetes_io_instance","hello-world"],["app_kubernetes_io_name","hello-world"],["cluster","helloworld"],["container","hello-world"],["job","grafana-agent\\/grafana-agent-pods"],["namespace","default"],["pod","hello-world-6f888bdd66-5gwtj"],["stream","stderr"]]}',
  stream: DataStream {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: true,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: [Circular *1],
      closed: true,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: null
    },
    _events: [Object: null prototype] { prefinish: [Function: prefinish] },
    _eventsCount: 1,
    _maxListeners: 14,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: true,
      ending: false,
      ended: false,
      finished: false,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 12,
      constructed: true,
      prefinished: false,
      errorEmitted: true,
      emitClose: true,
      autoDestroy: true,
      errored: [Circular *1],
      closed: true,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    _tapped: false,
    _error_handlers: [],
    _scramjet_options: {
      referrer: StringStream {
        _readableState: ReadableState {
          objectMode: true,
          highWaterMark: 16,
          buffer: BufferList { head: [Object], tail: [Object], length: 1 },
          length: 1,
          pipes: [],
          flowing: false,
          ended: false,
          endEmitted: false,
          reading: true,
          constructed: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          destroyed: false,
          errored: null,
          closed: false,
          closeEmitted: false,
          defaultEncoding: 'utf8',
          awaitDrainWriters: null,
          multiAwaitDrain: false,
          readingMore: false,
          dataEmitted: true,
          decoder: null,
          encoding: null,
          [Symbol(kPaused)]: true
        },
        _events: [Object: null prototype] {
          prefinish: [Function: prefinish],
          unpipe: [Function: onunpipe],
          error: [ [Function: onerror], [Function (anonymous)] ],
          close: [Function: bound onceWrapper] {
            listener: [Function: onclose]
          },
          finish: [Function: bound onceWrapper] {
            listener: [Function: onfinish]
          },
          drain: [Function: pipeOnDrainFunctionResult]
        },
        _eventsCount: 6,
        _maxListeners: 14,
        _writableState: WritableState {
          objectMode: true,
          highWaterMark: 16,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: true,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 0,
          constructed: true,
          prefinished: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          errored: null,
          closed: false,
          closeEmitted: false,
          [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: true,
        _tapped: true,
        _error_handlers: [ [AsyncFunction (anonymous)] ],
        _scramjet_options: {
          referrer: StringStream {
            _readableState: [ReadableState],
            _events: [Object: null prototype],
            _eventsCount: 7,
            _maxListeners: 14,
            _writableState: [WritableState],
            allowHalfOpen: true,
            _transform: [Function: transform],
            _flush: [Function: flush],
            _tapped: true,
            _error_handlers: [Array],
            _scramjet_options: [Object],
            seq: 18,
            type: 'Transform-',
            TimeSource: [Function: Date],
            setTimeout: [Function],
            clearTimeout: [Function: clearTimeout],
            buffer: '{"string":"{\\"timestamp\\":\\"2023-08-21T12:57:31.685772Z\\",\\"http_method\\":\\"-\\",\\"http_path\\":\\"-\\",\\"http_host\\":\\"-\\",\\"status\\":\\"-\\",\\"service_name\\":\\"hello-world\\",\\"service_version\\":\\"0.1.50\\",\\"traceid\\":\\"908765dd-da5c-4f54-a556-65e070e47b84\\",\\"level\\":\\"debug\\",\\"event\\":\\"signature\\",\\"request_headers\\":\\"-\\",\\"request_body\\":\\"-\\",\\"response_body\\":\\"-\\",\\"response_headers\\":\\"-\\",\\"duration\\":\\"-\\",\\"invoice_id\\":\\"-\\",\\"message\\":\\"fOvhmjWwnesFHkDm5HmpZFjQ5ETFj0KG5D_n8sZ8eH0\\",\\"log_type\\":\\"internal\\"}","fingerprint":"8745452314534852165","timestamp_ns":"16926226516858',
            encoding: 'utf8',
            [Symbol(kCapture)]: false,
            [Symbol(kCallback)]: null
          },
          constructed: 'Error\n' +
            '    at new PromiseTransformStream (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:65:27)\n' +
            '    at new DataStream (/app/node_modules/scramjet-core/lib/data-stream.js:43:9)\n' +
            '    at new StringStream (/app/node_modules/scramjet-core/lib/string-stream.js:34:9)\n' +
            '    at StringStream._selfInstance (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:344:16)\n' +
            '    at StringStream.endWith (/app/node_modules/scramjet/lib/data-stream.js:245:31)\n' +
            '    at preprocessStream (/app/lib/db/clickhouse.js:815:59)\n' +
            '    at queryFingerprintsScan (/app/lib/db/clickhouse.js:369:22)\n' +
            '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
            '    at async Object.handler (/app/lib/handlers/query_range.js:40:22)',
          objectMode: true,
          promiseRead: null,
          promiseWrite: null,
          promiseTransform: [Function: promiseTransform],
          promiseFlush: [Function: flushPromise],
          beforeTransform: null,
          afterTransform: null,
          writableObjectMode: true,
          readableObjectMode: true,
          transforms: [ [Function] ],
          runFlush: [Function: flushPromise]
        },
        seq: 19,
        type: 'Transform',
        _transform: [Function (anonymous)],
        _flush: [Function (anonymous)],
        TimeSource: [Function: Date],
        setTimeout: [Function: setTimeout] {
          [Symbol(nodejs.util.promisify.custom)]: [Getter]
        },
        clearTimeout: [Function: clearTimeout],
        buffer: '',
        encoding: 'utf8',
        [Symbol(kCapture)]: false,
        [Symbol(kCallback)]: null
      },
      constructed: 'Error\n' +
        '    at new PromiseTransformStream (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:65:27)\n' +
        '    at new DataStream (/app/node_modules/scramjet-core/lib/data-stream.js:43:9)\n' +
        '    at StringStream.map (/app/node_modules/scramjet-core/lib/data-stream.js:197:26)\n' +
        '    at preprocessStream (/app/lib/db/clickhouse.js:816:6)\n' +
        '    at queryFingerprintsScan (/app/lib/db/clickhouse.js:369:22)\n' +
        '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
        '    at async Object.handler (/app/lib/handlers/query_range.js:40:22)',
      objectMode: true,
      promiseRead: null,
      promiseWrite: null,
      promiseTransform: [Function (anonymous)],
      promiseFlush: null,
      beforeTransform: null,
      afterTransform: null,
      writableObjectMode: true,
      readableObjectMode: true,
      transforms: [
        [Function: bound ] { ref: [Function (anonymous)] },
        [Function: bound ] { ref: [Function (anonymous)] },
        [Function: bound ] { ref: [Function (anonymous)] },
        [AsyncFunction (anonymous)] { ref: [Function (anonymous)] }
      ]
    },
    seq: 20,
    type: 'Transform',
    _transform: [Function (anonymous)],
    _flush: [Function (anonymous)],
    TimeSource: [Function: Date],
    setTimeout: [Function: setTimeout] {
      [Symbol(nodejs.util.promisify.custom)]: [Getter]
    },
    clearTimeout: [Function: clearTimeout],
    buffer: null,
    [Symbol(kCapture)]: false,
    [Symbol(kCallback)]: null
  },
  code: 'ERR_SCRAMJET_EXTERNAL',
  cause: TypeError: Cannot read properties of undefined (reading 'EOF')
      at module.exports.isEOF (/app/parser/registry/common.js:121:37)
      at DataStream.<anonymous> (/app/parser/registry/stream_selector_operator_registry/stream_selector_operator_registry.js:240:17)
      at /app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:322:56
      at async Promise.all (index 0),
  constructor: [class StreamError extends Error]
}
npm notice
npm notice New major version of npm available! 8.19.4 -> 9.8.1
npm notice Changelog: <https://github.com/npm/cli/releases/tag/v9.8.1>
npm notice Run `npm install -g npm@9.8.1` to update!
npm notice
```
</details>

Qryn version: ghcr.io/metrico/qryn:v2.3.11
Clickhouse version: v23.7.4

Logs push via grafana-agent.

As i understand problem with parse `json` break qryn - that incorrect

**Comment by akvlad** [comment]
I see a bug.

For now please change your request:
` | json ` -> ` json app_kubernetes_io_name="app.kubernetes.io.name" ` 
`app.kubernetes.io.name` - the json path to the value you look for

**Comment by akvlad** [comment]
parameterized json is much more stable and fast.

**Comment by xom4ek** [comment]
<img width="1392" alt="image" src="https://github.com/metrico/qryn/assets/29627495/015033d8-168b-43cd-9551-ad9b8e428c91">
```
{"level":50,"time":1692626185659,"pid":20,"hostname":"qryn-7d9bb45b4b-wkqdd","name":"qryn","reqId":"req-8lu","err":"Cannot read properties of null (reading 'rootToken')\nTypeError: Cannot read properties of null (reading 'rootToken')\n    at /app/parser/registry/parser_registry/json.js:28:13\n    at Array.reduce (<anonymous>)\n    at /app/parser/registry/parser_registry/json.js:24:40\n    at Object.module.exports.viaClickhouseQuery (/app/parser/registry/parser_registry/json.js:44:18)\n    at Object.json (/app/parser/registry/parser_registry/index.js:19:17)\n    at Object.module.exports.transpileLogStreamSelector (/app/parser/transpiler.js:411:33)\n    at Object.module.exports.transpile (/app/parser/transpiler.js:197:37)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:227:29)\n    at Object.handler (/app/lib/handlers/query_range.js:40:33)\n    at runMicrotasks (<anonymous>)","msg":"Cannot read properties of null (reading 'rootToken')"}
{"level":50,"time":1692626185668,"pid":20,"hostname":"qryn-7d9bb45b4b-wkqdd","name":"qryn","reqId":"req-8lu","err":"Cannot read properties of null (reading 'rootToken')\nTypeError: Cannot read properties of null (reading 'rootToken')\n    at /app/parser/registry/parser_registry/json.js:28:13\n    at Array.reduce (<anonymous>)\n    at /app/parser/registry/parser_registry/json.js:24:40\n    at Object.module.exports.viaClickhouseQuery (/app/parser/registry/parser_registry/json.js:44:18)\n    at Object.json (/app/parser/registry/parser_registry/index.js:19:17)\n    at Object.module.exports.transpileLogStreamSelector (/app/parser/transpiler.js:411:33)\n    at Object.module.exports.transpile (/app/parser/transpiler.js:197:37)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:227:29)\n    at Object.handler (/app/lib/handlers/query_range.js:40:33)\n    at runMicrotasks (<anonymous>)","msg":"Cannot read properties of null (reading 'rootToken')"}
{"level":30,"time":1692626185669,"pid":20,"hostname":"qryn-7d9bb45b4b-wkqdd","name":"qryn","reqId":"req-8lu","res":{"statusCode":500},"responseTime":65.73988914489746,"msg":"request completed"}
{"level":30,"time":1692626185670,"pid":20,"hostname":"qryn-7d9bb45b4b-wkqdd","name":"qryn","reqId":"req-8lr","res":{"statusCode":204},"responseTime":152.2164831161499,"msg":"request completed"}
{"level":30,"time":1692626185670,"pid":20,"hostname":"qryn-7d9bb45b4b-wkqdd","name":"qryn","reqId":"req-8ls","res":{"statusCode":204},"responseTime":123.90023708343506,"msg":"request completed"}
{"level":30,"time":1692626185683,"pid":20,"hostname":"qryn-7d9bb45b4b-wkqdd","name":"qryn","reqId":"req-8lv","req":{"method":"GET","url":"/loki/api/v1/query_range?direction=backward&end=1692626185368000000&limit=1000&query=sum+by+%28level%29+%28count_over_time%28%7Bcluster%3D%22helloworld%22%7D+%7C+json+app_kubernetes_io_instance%3D%22hello-world%22%5B1m%5D%29%29&start=1692622585368000000&step=60000ms","hostname":"qryn.qryn.svc:3100","remoteAddress":"10.0.4.131","remotePort":50888},"msg":"incoming request"}
Couldn't execute script:
Expected [ or 'EOF' ] @1:6 encountered 'e-a'.
hello-world
{"level":50,"time":1692626185708,"pid":20,"hostname":"qryn-7d9bb45b4b-wkqdd","name":"qryn","reqId":"req-8lv","err":"Cannot read properties of null (reading 'rootToken')\nTypeError: Cannot read properties of null (reading 'rootToken')\n    at /app/parser/registry/parser_registry/json.js:28:13\n    at Array.reduce (<anonymous>)\n    at /app/parser/registry/parser_registry/json.js:24:40\n    at Object.module.exports.viaClickhouseQuery (/app/parser/registry/parser_registry/json.js:44:18)\n    at Object.json (/app/parser/registry/parser_registry/index.js:19:17)\n    at Object.module.exports.transpileLogStreamSelector (/app/parser/transpiler.js:411:33)\n    at Object.module.exports.transpileLogRangeAggregation (/app/parser/transpiler.js:387:26)\n    at Object.module.exports.transpileAggregationOperator (/app/parser/transpiler.js:372:28)\n    at Object.module.exports.transpile (/app/parser/transpiler.js:184:30)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:227:29)","msg":"Cannot read properties of null (reading 'rootToken')"}
{"level":50,"time":1692626185708,"pid":20,"hostname":"qryn-7d9bb45b4b-wkqdd","name":"qryn","reqId":"req-8lv","err":"Cannot read properties of null (reading 'rootToken')\nTypeError: Cannot read properties of null (reading 'rootToken')\n    at /app/parser/registry/parser_registry/json.js:28:13\n    at Array.reduce (<anonymous>)\n    at /app/parser/registry/parser_registry/json.js:24:40\n    at Object.module.exports.viaClickhouseQuery (/app/parser/registry/parser_registry/json.js:44:18)\n    at Object.json (/app/parser/registry/parser_registry/index.js:19:17)\n    at Object.module.exports.transpileLogStreamSelector (/app/parser/transpiler.js:411:33)\n    at Object.module.exports.transpileLogRangeAggregation (/app/parser/transpiler.js:387:26)\n    at Object.module.exports.transpileAggregationOperator (/app/parser/transpiler.js:372:28)\n    at Object.module.exports.transpile (/app/parser/transpiler.js:184:30)\n    at Object.scanFingerprints (/app/lib/db/clickhouse.js:227:29)","msg":"Cannot read properties of null (reading 'rootToken')"}
```

Another think but still didnt work.


when usage 
`{cluster="helloworld"} | json | app_kubernetes_io_instance="helloworld"` some times its work - but i suppose when qryn try parse something incorrect with json that broken

**Comment by akvlad** [comment]
The suggestion was
`{cluster="helloworld"} | json app_kubernetes_io_name = "app.kubernetes.io.name" | app_kubernetes_io_name = "hello-world"`

**Comment by akvlad** [comment]
Fixed.
parameterless `| json ` should be ok as well since v2.3.12. Please recheck.

**Comment by xom4ek** [comment]
May be i found every time new bug - but seems like proble rise again)

version: ghcr.io/metrico/qryn:v2.3.12

<img width="751" alt="image" src="https://github.com/metrico/qryn/assets/29627495/90cd5f1a-1a55-4444-8818-b005000bbae9">

```logs
eq-7tx","res":{"statusCode":204},"responseTime":40.781635999679565,"msg":"request completed"}
node:events:491
      throw er; // Unhandled 'error' event
      ^

<ref *1> StreamError: Cannot read properties of undefined (reading 'labels')
    at /app/node_modules/scramjet-core/lib/util/mk-transform.js:59:44
    at runMicrotasks (<anonymous>)
    at runNextTicks (node:internal/process/task_queues:61:5)
    at processImmediate (node:internal/timers:437:9)
  caused by:
    at DataStream.<anonymous> (/app/parser/registry/stream_selector_operator_registry/stream_selector_operator_registry.js:121:19)
    ... 4 lines matching cause stack trace ...
    at async Promise.all (index 0)
  --- raised in DataStream(76) constructed ---
    at new PromiseTransformStream (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:65:27)
    at new DataStream (/app/node_modules/scramjet-core/lib/data-stream.js:43:9)
    at StringStream.map (/app/node_modules/scramjet-core/lib/data-stream.js:197:26)
    at preprocessStream (/app/lib/db/clickhouse.js:816:6)
    at queryFingerprintsScan (/app/lib/db/clickhouse.js:369:22)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Object.handler (/app/lib/handlers/query_range.js:40:22) {
  chunk: '{"string":"  warnings.warn(","fingerprint":"727331745929350279","timestamp_ns":"1692793067052086784","labels":[["app_kubernetes_io_instance","helloworld-selector"],["app_kubernetes_io_name","helloworld-selector"],["cluster","helloworld"],["container","helloworld-selector"],["job","grafana-agent\\/grafana-agent-pods"],["namespace","default"],["pod","helloworld-selector-6f888bdd66-qz2g7"],["stream","stderr"]]}',
  stream: DataStream {
    _readableState: ReadableState {
      objectMode: true,
      highWaterMark: 16,
      buffer: BufferList { head: null, tail: null, length: 0 },
      length: 0,
      pipes: [],
      flowing: null,
      ended: false,
      endEmitted: false,
      reading: false,
      constructed: true,
      sync: false,
      needReadable: false,
      emittedReadable: false,
      readableListening: false,
      resumeScheduled: false,
      errorEmitted: true,
      emitClose: true,
      autoDestroy: true,
      destroyed: true,
      errored: [Circular *1],
      closed: true,
      closeEmitted: false,
      defaultEncoding: 'utf8',
      awaitDrainWriters: null,
      multiAwaitDrain: false,
      readingMore: false,
      dataEmitted: false,
      decoder: null,
      encoding: null,
      [Symbol(kPaused)]: null
    },
    _events: [Object: null prototype] { prefinish: [Function: prefinish] },
    _eventsCount: 1,
    _maxListeners: 14,
    _writableState: WritableState {
      objectMode: true,
      highWaterMark: 16,
      finalCalled: false,
      needDrain: false,
      ending: false,
      ended: false,
      finished: false,
      destroyed: true,
      decodeStrings: true,
      defaultEncoding: 'utf8',
      length: 0,
      writing: false,
      corked: 0,
      sync: false,
      bufferProcessing: false,
      onwrite: [Function: bound onwrite],
      writecb: null,
      writelen: 0,
      afterWriteTickInfo: null,
      buffered: [],
      bufferedIndex: 0,
      allBuffers: true,
      allNoop: true,
      pendingcb: 4,
      constructed: true,
      prefinished: false,
      errorEmitted: true,
      emitClose: true,
      autoDestroy: true,
      errored: [Circular *1],
      closed: true,
      closeEmitted: false,
      [Symbol(kOnFinished)]: []
    },
    allowHalfOpen: true,
    _tapped: false,
    _error_handlers: [],
    _scramjet_options: {
      referrer: StringStream {
        _readableState: ReadableState {
          objectMode: true,
          highWaterMark: 16,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: [],
          flowing: false,
          ended: false,
          endEmitted: false,
          reading: true,
          constructed: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          destroyed: false,
          errored: null,
          closed: false,
          closeEmitted: false,
          defaultEncoding: 'utf8',
          awaitDrainWriters: null,
          multiAwaitDrain: false,
          readingMore: false,
          dataEmitted: true,
          decoder: null,
          encoding: null,
          [Symbol(kPaused)]: true
        },
        _events: [Object: null prototype] {
          prefinish: [Function: prefinish],
          unpipe: [Function: onunpipe],
          error: [ [Function: onerror], [Function (anonymous)] ],
          close: [Function: bound onceWrapper] {
            listener: [Function: onclose]
          },
          finish: [Function: bound onceWrapper] {
            listener: [Function: onfinish]
          }
        },
        _eventsCount: 5,
        _maxListeners: 14,
        _writableState: WritableState {
          objectMode: true,
          highWaterMark: 16,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: false,
          decodeStrings: true,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 0,
          constructed: true,
          prefinished: false,
          errorEmitted: false,
          emitClose: true,
          autoDestroy: true,
          errored: null,
          closed: false,
          closeEmitted: false,
          [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: true,
        _tapped: true,
        _error_handlers: [ [AsyncFunction (anonymous)] ],
        _scramjet_options: {
          referrer: StringStream {
            _readableState: [ReadableState],
            _events: [Object: null prototype],
            _eventsCount: 7,
            _maxListeners: 14,
            _writableState: [WritableState],
            allowHalfOpen: true,
            _transform: [Function: transform],
            _flush: [Function: flush],
            _tapped: true,
            _error_handlers: [Array],
            _scramjet_options: [Object],
            seq: 74,
            type: 'Transform-',
            TimeSource: [Function: Date],
            setTimeout: [Function],
            clearTimeout: [Function: clearTimeout],
            buffer: '',
            encoding: 'utf8',
            [Symbol(kCapture)]: false,
            [Symbol(kCallback)]: null
          },
          constructed: 'Error\n' +
            '    at new PromiseTransformStream (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:65:27)\n' +
            '    at new DataStream (/app/node_modules/scramjet-core/lib/data-stream.js:43:9)\n' +
            '    at new StringStream (/app/node_modules/scramjet-core/lib/string-stream.js:34:9)\n' +
            '    at StringStream._selfInstance (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:344:16)\n' +
            '    at StringStream.endWith (/app/node_modules/scramjet/lib/data-stream.js:245:31)\n' +
            '    at preprocessStream (/app/lib/db/clickhouse.js:815:59)\n' +
            '    at queryFingerprintsScan (/app/lib/db/clickhouse.js:369:22)\n' +
            '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
            '    at async Object.handler (/app/lib/handlers/query_range.js:40:22)',
          objectMode: true,
          promiseRead: null,
          promiseWrite: null,
          promiseTransform: [Function: promiseTransform],
          promiseFlush: [Function: flushPromise],
          beforeTransform: null,
          afterTransform: null,
          writableObjectMode: true,
          readableObjectMode: true,
          transforms: [ [Function] ],
          runFlush: [Function: flushPromise]
        },
        seq: 75,
        type: 'Transform',
        _transform: [Function (anonymous)],
        _flush: [Function (anonymous)],
        TimeSource: [Function: Date],
        setTimeout: [Function: setTimeout] {
          [Symbol(nodejs.util.promisify.custom)]: [Getter]
        },
        clearTimeout: [Function: clearTimeout],
        buffer: '',
        encoding: 'utf8',
        [Symbol(kCapture)]: false,
        [Symbol(kCallback)]: null
      },
      constructed: 'Error\n' +
        '    at new PromiseTransformStream (/app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:65:27)\n' +
        '    at new DataStream (/app/node_modules/scramjet-core/lib/data-stream.js:43:9)\n' +
        '    at StringStream.map (/app/node_modules/scramjet-core/lib/data-stream.js:197:26)\n' +
        '    at preprocessStream (/app/lib/db/clickhouse.js:816:6)\n' +
        '    at queryFingerprintsScan (/app/lib/db/clickhouse.js:369:22)\n' +
        '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n' +
        '    at async Object.handler (/app/lib/handlers/query_range.js:40:22)',
      objectMode: true,
      promiseRead: null,
      promiseWrite: null,
      promiseTransform: [Function (anonymous)],
      promiseFlush: null,
      beforeTransform: null,
      afterTransform: null,
      writableObjectMode: true,
      readableObjectMode: true,
      transforms: [
        [Function: bound ] { ref: [Function (anonymous)] },
        [Function: bound ] { ref: [Function (anonymous)] },
        [Function: bound ] { ref: [Function (anonymous)] },
        [AsyncFunction (anonymous)] { ref: [Function (anonymous)] }
      ]
    },
    seq: 76,
    type: 'Transform',
    _transform: [Function (anonymous)],
    _flush: [Function (anonymous)],
    TimeSource: [Function: Date],
    setTimeout: [Function: setTimeout] {
      [Symbol(nodejs.util.promisify.custom)]: [Getter]
    },
    clearTimeout: [Function: clearTimeout],
    buffer: null,
    [Symbol(kCapture)]: false,
    [Symbol(kCallback)]: null
  },
  code: 'ERR_SCRAMJET_EXTERNAL',
  cause: TypeError: Cannot read properties of undefined (reading 'labels')
      at DataStream.<anonymous> (/app/parser/registry/stream_selector_operator_registry/stream_selector_operator_registry.js:121:19)
      at /app/node_modules/scramjet-core/lib/util/promise-transform-stream.js:322:56
      at runMicrotasks (<anonymous>)
      at runNextTicks (node:internal/process/task_queues:61:5)
      at processImmediate (node:internal/timers:437:9)
      at async Promise.all (index 0),
  constructor: [class StreamError extends Error]
}
```

**Comment by akvlad** [comment]
@xom4ek I see the bug. For now please use `!~` instead of `!=` . 
Fixing.
