### ISSUE TITLE
qryn + bun

### ISSUE THREAD

**Issue by lmangani** [metrico/qryn#346]
Since bun 1.0 has been released, it's time to make qryn work with it and take advantage of its speed. 
This thread will capture some issues and adaptions required for the migration to succeed.

**Comment by lmangani** [comment]
Bun is able to install and start qryn, serving basic requests such as labels.values while actual queries are failing with to the following error:

```
11 |     // Since node 6.3.0 state.buffer is a BufferList not an array
12 |     if (state.buffer.head) {
13 |       return state.buffer.head.data.length
14 |     }
15 |
16 |     return state.buffer[0].length
               ^
TypeError: undefined is not an object (evaluating 'state.buffer[0].length')
      at getStateLength (/app/node_modules/stream-shift/index.js:16:11)
      at shift (/app/node_modules/stream-shift/index.js:6:98)
      at /app/node_modules/peek-stream/node_modules/duplexify/index.js:168:34
      at onreadable (/app/node_modules/peek-stream/node_modules/duplexify/index.js:134:4)
      at processTicksAndRejections (:1:2602)
```

**Comment by lmangani** [comment]
Implemented in 3.x and ready for user testing and feedback
