### ISSUE TITLE
Wrong statuscode when Database push error

### ISSUE THREAD

**Issue by bds-congnguyen** [metrico/qryn#415]
Hi there,
I'm testing case QRYN up but Clickhouse down and I noticed that
```
{"level":50,"time":1703221367495,"pid":24,"hostname":"54ae61ff3d3e","name":"qryn"}
{"level":50,"time":1703221367496,"pid":24,"hostname":"54ae61ff3d3e","name":"qryn","err":"Database push error\nError: Database push error\n    at Worker.<anonymous> (/app/lib/db/clickhouse.js:80:27)\n    at Worker.emit (node:events:514:28)\n    at MessagePort.<anonymous> (node:internal/worker:263:53)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)\n    at exports.emitMessage (node:internal/per_context/messageport:23:28)","msg":"Database push error"}
{"level":30,"time":1703221367496,"pid":24,"hostname":"54ae61ff3d3e","name":"qryn","reqId":"req-3ik","res":{"statusCode":204},"responseTime":79.97018384933472,"msg":"request completed"}
{"level":50,"time":1703221367495,"pid":24,"hostname":"54ae61ff3d3e","name":"qryn"}
{"level":30,"time":1703221367860,"pid":24,"hostname":"54ae61ff3d3e","name":"qryn","reqId":"req-3il","req":{"method":"POST","url":"/loki/api/v1/push","hostname":"x.x.x.x:3100","remoteAddress":"x.x.x.x","remotePort":53196},"msg":"incoming request"}
```

what's my expected is when `Database push error` happening, then Qryn should return error code 5xx instead of 204.
because client like Promtail,GrafanaAgent,vector will look on response status code, if response code is 204 then client will acknowledge that send event succeeded then remove log event out of buffer and move to next checkpoint.
that'll cause log become lost.

**Comment by bds-congnguyen** [comment]
I think return status code `204` is default behavior without considering response of function `push`
https://github.com/metrico/qryn/blob/master/lib/handlers/push.js#L137

**Comment by akvlad** [comment]
@bds-congnguyen 
[3.0.27](https://github.com/metrico/qryn/releases/tag/3.0.27)
should fix the issue.
Sorry for the inconvenience.

**Comment by bds-congnguyen** [comment]
Hi @akvlad 
confirmed that issue has been fixed
here is log from Qryn
```
compose-qryn-1  | {"level":50,"time":1703555797783,"pid":25,"hostname":"48db5ccb1a33","name":"qryn","reqId":"req-52","err":"Database push error\nError: Database push error\n    at Worker.<anonymous> (/app/lib/db/clickhouse.js:80:27)\n    at Worker.emit (node:events:514:28)\n    at MessagePort.<anonymous> (node:internal/worker:263:53)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:814:20)\n    at exports.emitMessage (node:internal/per_context/messageport:23:28)","msg":"Database push error"}
compose-qryn-1  | {"level":30,"time":1703555797783,"pid":25,"hostname":"48db5ccb1a33","name":"qryn","reqId":"req-52","res":{"statusCode":500},"responseTime":28.770941734313965,"msg":"request completed"}
```
and client was sent log to buffer after meet error code 500 as expected, example log from vector.dev
```
Dec 26 08:59:00 sample vector[1518107]: 2023-12-26T01:59:00.748193Z DEBUG sink{component_kind="sink" component_id=file_logs component_type=loki}:request{request_id=320208}:http: vector::internal_events::http_client: HTTP response. status=500 Internal Server Error version=HTTP/1.1 headers={"vary": "Origin, accept-encoding", "access-control-allow-origin": "*", "content-type": "application/json; charset=utf-8", "content-length": "84", "date": "Tue, 26 Dec 2023 01:59:00 GMT", "connection": "keep-alive", "keep-alive": "timeout=72"} body=[84 bytes]
Dec 26 08:59:00 sample vector[1518107]: 2023-12-26T01:59:00.748258Z  WARN sink{component_kind="sink" component_id=file_logs component_type=loki}:request{request_id=320208}: vector::sinks::util::retries: Retrying after error. error=Server responded with an error: 500 Internal Server Error internal_log_rate_limit=true
Dec 26 08:59:00 sample vector[1518107]: 2023-12-26T01:59:00.748264Z DEBUG sink{component_kind="sink" component_id=file_logs component_type=loki}:request{request_id=320208}: vector::sinks::util::retries: Retrying request. delay_ms=144000
Dec 26 08:59:01 sample vector[1518107]: 2023-12-26T01:59:01.629848Z DEBUG source{component_kind="source" component_id=logs component_type=file}:file_server: file_source::file_server: event_throughput=258.000/sec bytes_throughput=151.409k/sec ratios={"discovery": 0.019089693, "other": 0.0033874414, "reading": 0.008813319, "sending": 0.01822758, "sleeping": 0.9504819}
Dec 26 08:59:01 sample vector[1518107]: 2023-12-26T01:59:01.659139Z DEBUG vector::internal_events::file::source: Files checkpointed. count=23 duration_ms=0
```
