### ISSUE TITLE
[bug] Error while adding Prometheus datasource in 3.1.x-bun

### ISSUE THREAD

**Issue by deathalt** [metrico/qryn#439]
```
 {"level":30,"time":1706258670966,"pid":1,"hostname":"qryn-read-64d8f49fb8-jdhwn","name":"qryn","msg":"http://localhost/api/v1/ Γöé
Γöé 20 |   }                                                                                                                                                 Γöé
Γöé 21 |   if (!req.query.query) {                                                                                                                           Γöé
Γöé 22 |     return res.send(resp)                                                                                                                           Γöé
Γöé 23 |   }                                                                                                                                                 Γöé
Γöé 24 |   if (req.query.query === '1+1') {                                                                                                                  Γöé
Γöé 25 |     return res.status(200).send(test())                                                                                                             Γöé
Γöé                 ^                                                                                                                                        Γöé
Γöé TypeError: res.status is not a function. (In 'res.status(200)', 'res.status' is undefined)                                                               Γöé
Γöé       at /app/lib/handlers/prom_query.js:25:12                                                                                                           Γöé
Γöé       at handler (/app/lib/handlers/prom_query.js:9:25)                                                                                                  Γöé
Γöé       at /app/lib/bun_wrapper.js:101:18                                                                                                                  Γöé
Γöé       at /app/lib/bun_wrapper.js:24:22                                                                                                                   Γöé
Γöé GET - /api/v1/query?query=1%2B1&time=4 failed                                                                                                            Γöé
Γöé {"level":30,"time":1706258670981,"pid":1,"hostname":"qryn-read-64d8f49fb8-jdhwn","name":"qryn","msg":"http://localhost/api/v1/ 

```

when I try to add qryn as prometheus datasource on 3.1.3-bun
on node version everything is ok

**Comment by akvlad** [comment]
Should be fixed in 3.2.0

**Comment by deathalt** [comment]
cannot reproduce on 3.2.0

**Comment by lmangani** [comment]
Thanks @akvlad 🖖
