### ISSUE TITLE
Post to /telegraf api produce an error

### ISSUE THREAD

**Issue by Friz-zy** [metrico/qryn#461]
I'm testing latest `qxip/qryn:bun` with telegraf. I couldn't get authorization work properly for `/influx/api/v2/write` as there is no info how to convert user and password into token and telegraf doesn't work with `user:password@url` schema for some reason. So I thought I'd give it a try `/telegraf` api with this telegraf config:
```
[[outputs.http]]
  url = "http://172.18.0.6:3100/telegraf"
  data_format = "json"
  method = "POST"
  username = "test"
  password = "test"
```

After qryn starting produce this error:
```
qryn  | {"level":30,"time":1707745060205,"pid":1,"hostname":"486e423b0d92","name":"qryn","msg":"http://172.18.0.6:3100/telegraf"}
qryn  | 146 |   add: (values) => {
qryn  | 147 |     return new Promise((resolve, reject) => {
qryn  | 148 |       const id = getThrottlerId()
qryn  | 149 |       throttler.postMessage({
qryn  | 150 |         type: 'labels',
qryn  | 151 |         data: values.map(r => JSON.stringify({
qryn  |                     ^
qryn  | TypeError: undefined is not a function (near '...values.map...')
qryn  |       at /app/lib/db/clickhouse.js:151:15
qryn  |       at new Promise (:1:21)
qryn  |       at add (/app/lib/db/clickhouse.js:147:12)
qryn  |       at /app/lib/handlers/telegraf.js:46:9
qryn  |       at forEach (:1:21)
qryn  |       at handler (/app/lib/handlers/telegraf.js:34:5)
qryn  |       at /app/lib/bun_wrapper.js:101:18
qryn  | 146 |   add: (values) => {
qryn  | 147 |     return new Promise((resolve, reject) => {
qryn  | 148 |       const id = getThrottlerId()
qryn  | 149 |       throttler.postMessage({
qryn  | 150 |         type: 'labels',
qryn  | 151 |         data: values.map(r => JSON.stringify({
```

**Comment by akvlad** [comment]
The `/telegraf` endpoint moved to `/influx` endpoint and discussed in the https://github.com/metrico/qryn/issues/462 .
We should consider removing it completely.

If there's no more complaints, let's close the issue.

**Comment by Friz-zy** [comment]
[wiki](https://github.com/metrico/qryn/wiki/Telegraf-HTTP-Input) should be updated then

**Comment by lmangani** [comment]
@Friz-zy the endpoint has been updated, although the instructions will need patching as well. Thanks!
