### ISSUE TITLE
Error when updating to 3.2.24

### ISSUE THREAD

**Issue by srolel** [metrico/qryn#527]
Hi, I get this error when querying from grafana in 3.2.24:

```
invalid wire type 4 at offset 3
Error: invalid wire type 4 at offset 3
 at Reader.skipType (/app/node_modules/protobufjs/src/reader.js:382:19)
 at Type.Status$decode [as decode] (eval at Codegen (/app/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:19:5)
 at Type.Span$decode [as decode] (eval at Codegen (/app/node_modules/@protobufjs/codegen/index.js:50:33), <anonymous>:73:22)
 at /app/traceql/post_processor/index.js:35:22
 at Array.map (<anonymous>)
 at /app/traceql/post_processor/index.js:28:23
 at Array.map (<anonymous>)
 at postProcess (/app/traceql/post_processor/index.js:26:15)
 at search (/app/traceql/index.js:43:9)
 at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by lmangani** [comment]
Thanks for the report @srolel which version did up upgrade from?

**Comment by srolel** [comment]
> Thanks for the report @srolel which version did up upgrade from? Also the query would help, unless its any query

I was on `qxip/qryn:latest` and saw the error after restarting the container today, so the upgrade was from 3.2.23. It appeared to be any query, e.g. just `{resource.service.name="service"}`

**Comment by lmangani** [comment]
Interesting. Our CI is not failing and neither is the k6 test. We'll do some deeper testing and investigation.

**Comment by akvlad** [comment]
Hello @srolel . 
There was a bug connected to ` | select ` pipe function.
The issue should be fixed in 3.2.25. Feel free to try.
Sorry fot the inconvenience.
